# permissions for end users to view arcades.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: arcade-viewer-role
rules:
- apiGroups:
  - game.marketplace.redhat.com
  resources:
  - arcades
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - game.marketplace.redhat.com
  resources:
  - arcades/status
  verbs:
  - get
