# permissions for end users to edit arcades.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: arcade-editor-role
rules:
- apiGroups:
  - game.marketplace.redhat.com
  resources:
  - arcades
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - game.marketplace.redhat.com
  resources:
  - arcades/status
  verbs:
  - get
